name: autoit_script_compiler
description: A Dart librariy for run and compile autoit script.
version: 1.0.0
repository: https://github.com/ASpurple/autoit_script_compiler

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
